# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e28978f1cc75c55624dbbb39c41e088c9f5ad95bb7eb343f5bc208b1ca69880b59e6bc6d79fc0724b1c081674524d7ada2fe5a66c16b7d6bc8e3328e5bed00b

test:
  secret_key_base: 8169fdf7ad23ca1fd7d6aa12b4ef6ed26eb835a5ebabbe4fd4f4d0b5aa788da4f448874913e96bbf96b25527d1b977fcecefa9b506dc86556a45065b2b60970a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
